import { Metadata } from 'next';
import './globals.css';
import { HighlightsProvider } from './dashboard/add-summary-for-today/context/HighlightsContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <HighlightsProvider>
        <body>{children}</body>
      </HighlightsProvider>
    </html>
  );
}
