import { Metadata } from 'next';
import './globals.css';
import { HighlightsProvider } from './dashboard/summary/context/HighlightsContext';
import { AcademicDataProvider } from './dashboard/summary/context/AcademicDataContext';
import { CodingDataProvider } from './dashboard/summary/context/CodingDataContext';
import { PersonalDataProvider } from './dashboard/summary/context/PersonalDataContext';
import { ThemeProvider } from '@/components/ui/theme-provider';
import { LearningsProvider } from './dashboard/summary/context/LearningsContext';
import { DiaryContextProvider } from './dashboard/summary/context/DiaryContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AcademicDataProvider>
        <CodingDataProvider>
          <PersonalDataProvider>
            <HighlightsProvider>
              <LearningsProvider>
                <DiaryContextProvider>
                  <body>
                    {/* <ThemeProvider
                  attribute="class"
                  // defaultTheme="system"
                  enableSystem
                  disableTransitionOnChange
                > */}
                    {children}
                    {/* </ThemeProvider> */}
                  </body>
                </DiaryContextProvider>
              </LearningsProvider>
            </HighlightsProvider>
          </PersonalDataProvider>
        </CodingDataProvider>
      </AcademicDataProvider>
    </html>
  );
}
