import { Metadata } from 'next';
import './globals.css';
import { HighlightsProvider } from './dashboard/add-summary-for-today/context/HighlightsContext';
import { AcademicDataProvider } from './dashboard/add-summary-for-today/context/AcademicDataContext';
import { CodingDataProvider } from './dashboard/add-summary-for-today/context/CodingDataContext';
import { PersonalDataProvider } from './dashboard/add-summary-for-today/context/PersonalDataContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AcademicDataProvider>
        <CodingDataProvider>
          <PersonalDataProvider>
            <HighlightsProvider>
              <body>{children}</body>
            </HighlightsProvider>
          </PersonalDataProvider>
        </CodingDataProvider>
      </AcademicDataProvider>
    </html>
  );
}
